package frames;

import javax.swing.*;
import java.awt.*;

public class ExportWindow {
    private JPanel exportWindowFrame;
    private JProgressBar exportProgressBar;
    private JLabel exportingLabel;

    public JPanel getExportWindowFrame() {
        return exportWindowFrame;
    }

    public JProgressBar getExportProgressBar() {
        return exportProgressBar;
    }

    public JLabel getExportingLabel() {
        return exportingLabel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        exportWindowFrame = new JPanel();
        exportWindowFrame.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        exportProgressBar = new JProgressBar();
        exportProgressBar.setValue(0);
        exportWindowFrame.add(exportProgressBar, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        exportingLabel = new JLabel();
        exportingLabel.setText("Exporting...");
        exportWindowFrame.add(exportingLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return exportWindowFrame;
    }

}
